# Generated by Django 3.2.6 on 2022-12-01 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchterm',
            old_name='last_serach',
            new_name='last_search',
        ),
    ]
